context:
  version: "1.6.66"

package:
  name: camport3
  version: ${{ version }}

source:
  url: https://github.com/percipioxyz/camport3/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d65260342e74afc7300e8cde448d2989202615c8a7321e6e426204daa95d5fe3

build:
  number: 1000

requirements:
  build:
  host:
    - libudev1
    - libusb
  run:

tests:
  - package_contents:
      include: 
        - camport3/TYApi.h
      lib:
        - libtycam.so

about:
  homepage: https://github.com/percipioxyz/camport3
  summary: Percipio Camera Software Development Kit
  description: This software development kit provides C/C++ API and sample applications to control and capture images from Percipio camera. The samples demonstrate how to get depth image, 3D point cloud , color and ir image from the depth camera. | 
    SDK sample's GUI needs Opencv2.4.8+. opencv dependency can be removed if if you do not need GUI.
